# ==========================================
# GMHelper CLI - Configuration File
# ==========================================
# Edit the values below to match your system.
# This file is sourced by gmhelper.sh at startup.

# Absolute path to the GarrysMod bin/linux64 directory
# (where gmad and gmpublish are located)
GMOD_BIN="/run/media/nap/5c9fedcc-bafb-4b4d-8f71-77262f56b6e8/SteamLibrary/steamapps/common/GarrysMod/bin/linux64"

# Default Work Folder — leave empty to always ask manually
WORK_FOLDER=""
